### ISSUE TITLE
[question] filtron request header size

### ISSUE THREAD

**Issue by tiekoetter** [searxng/filtron#6] opened 2022-01-08 00:39 UTC
I have a problem where if I search a string that is longer than 120 character it gets rejected by filtron.

Example:
``search?q=ayIWuCsmIV0OiwMvQ7h5bTuMP2mxzhfVZJX7ulmeyIAYfOMeYUwa0J4VNU3rDwZBncYwlPYYg7dIaFq8pPQnESYuZsTbe4L4biuqHqJGXnwO896V2MObqeeZ`` works correctly.
``search?q=ayIWuCsmIV0OiwMvQ7h5bTuMP2mxzhfVZJX7ulmeyIAYfOMeYUwa0J4VNU3rDwZBncYwlPYYg7dIaFq8pPQnESYuZsTbe4L4biuqHqJGXnwO896V2MObqeeZa`` gets rejected with error ``Too big request header``

I can't reproduce this on my test server with identical filtron and SearXNG setup.
There is also nothing getting logged. When I inspect filtron with debugging enabled I can see every other request but as soon as this string length limit is reached the request won't even be logged.

What should I do now?

**Comment by return42** [comment] 2022-01-10 14:39
> When I inspect filtron with debugging enabled I can see every other request but as soon as this string length limit is reached the request won't even be logged.

May be the `Too big request header` is from your HTTP server and not from your filtron?

Do you have a Web Application Firewall (WAF) like ModSecurity or any other special HTTP server setup?

**Comment by tiekoetter** [comment] 2022-01-10 20:15
@return42 I have already fixed the issue. It was the fasthttp ReadBufferSize in filtron.

**Comment by dalf** [comment] 2022-01-10 21:36
https://github.com/searxng/filtron/blob/5624108d95ecbd192774afde14cbaf4e0dad630e/filtron.go#L20

try to add the parameter `--read-buffer-size 65536` to the command line that starts filtron.

**Comment by tiekoetter** [comment] 2022-01-10 21:59
@dalf Thanks but I already fixed it. It is exactly what you described.

**Comment by return42** [comment] 2022-01-10 22:10
OK, now I know why I can't reproduce the example from above .. the buffer size is to small when preferences are save and the search term is long enough.

> try to add the parameter `--read-buffer-size 65536` to the command line that starts filtron.

I will send a PR to adjust buffer size in [utils/templates/lib/systemd/system/filtron.service#L13](https://github.com/searxng/searxng/blob/7cdb86ba951766d807130f4e8af5190789c2e690/utils/templates/lib/systemd/system/filtron.service#L13)

**Comment by return42** [comment] 2022-01-10 22:31
@tiekoetter I send PR https://github.com/searxng/searxng/pull/738 / I close this issue now.

**Closed** 2022-01-10 22:35 UTC
